# set base image
FROM python:3.8.12-slim AS base

# maintainer details
LABEL maintainer="Soumithri Chilakamarri <soumithri93@gmail.com>"

# Stop python from generating .pyc files and
# enable tracebacks on segfaults
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONFAULTHANDLER 1
ENV PYTHONUNBUFFERED 1

# copy dependencies file into working directory
COPY requirements-api.txt .

# install pip dependencies
RUN pip install -r requirements-api.txt

# copy project
COPY . .